# Generated by Django 2.1.5 on 2019-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('outer_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inner_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modulus_elasticity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('connectivity_table', models.TextField()),
                ('nodal_coordinates', models.TextField()),
                ('boundary_conditions', models.TextField()),
                ('frame_or_truss', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OutputStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nodal_coordinates', models.TextField()),
                ('factor_of_safety', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
