# Generated by Django 2.1.5 on 2019-01-10 23:10

import FEA2D.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputOutputLink',
            fields=[
                ('id', models.BigIntegerField(default=FEA2D.models.gen_id, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('input_id', models.BigIntegerField()),
                ('output_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='outputstructure',
            name='factor_of_safety',
        ),
        migrations.AddField(
            model_name='outputstructure',
            name='stress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputstructure',
            name='id',
            field=models.BigIntegerField(default=FEA2D.models.gen_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outputstructure',
            name='id',
            field=models.BigIntegerField(default=FEA2D.models.gen_id, primary_key=True, serialize=False),
        ),
    ]
