# Generated by Django 2.1.5 on 2019-01-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0002_auto_20190110_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputstructure',
            name='force_vector',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
