# Generated by Django 2.1.5 on 2019-01-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0004_auto_20190110_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputoutputlink',
            old_name='input_id',
            new_name='inputid',
        ),
        migrations.RenameField(
            model_name='inputoutputlink',
            old_name='output_id',
            new_name='outputid',
        ),
    ]
