# Generated by Django 2.1.5 on 2019-01-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0005_auto_20190110_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputoutputlink',
            old_name='inputid',
            new_name='input_id',
        ),
        migrations.RenameField(
            model_name='inputoutputlink',
            old_name='outputid',
            new_name='output_id',
        ),
    ]
