# Generated by Django 2.1.5 on 2019-01-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0006_auto_20190110_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputstructure',
            name='ip_address',
        ),
    ]
