# Generated by Django 2.1.5 on 2019-01-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEA2D', '0007_remove_inputstructure_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputstructure',
            name='yield_strength',
        ),
    ]
